#!/usr/bin/env bash
set -euo pipefail

APPNAME="poste-dev"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/$APPNAME"
PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# Generate init.lua with project root embedded (always refresh)
mkdir -p "$CONFIG_DIR"
cat > "$CONFIG_DIR/init.lua" << LUA
-- poste-dev/init.lua — generated by dev/start.sh
-- Edit dev/deps.lua or dev/config.lua (no re-setup needed)

local ROOT = "${PROJECT_ROOT//\"/\\\"}"

-- Bootstrap lazy.nvim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.uv.fs_stat(lazypath) then
  vim.fn.system({
    "git", "clone", "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

-- Load general settings from dev/settings.lua (live)
pcall(dofile, ROOT .. "/dev/settings.lua")

-- Load external dependencies from dev/deps.lua (live)
local plugins = {}
local deps_ok, deps = pcall(dofile, ROOT .. "/dev/deps.lua")
if deps_ok and type(deps) == "table" then
  plugins = deps
end
require("lazy").setup(plugins, {
  root = vim.fn.stdpath("data") .. "/lazy",
  defaults = { lazy = false },
})

-- Load Poste from project source
vim.opt.rtp:prepend(ROOT)

-- Auto-detect locally built poste binary (no separate build needed)
local binary_path
for _, p in ipairs({ ROOT .. "/target/debug/poste", ROOT .. "/target/release/poste" }) do
  if vim.uv.fs_stat(p) then
    binary_path = p
    break
  end
end

-- Load user config from dev/config.lua (live)
local cfg_ok, cfg = pcall(dofile, ROOT .. "/dev/config.lua")
if not cfg_ok or type(cfg) ~= "table" then cfg = {} end
if binary_path then cfg.poste_binary = binary_path end
require("poste").setup(cfg)
LUA
echo "  Generated: $CONFIG_DIR/init.lua"

# Launch nvim
exec env NVIM_APPNAME="$APPNAME" nvim "$@"
