-- Unit tests for detect_context()
-- Tests all completion context types: method, method_or_header, header_value, variable, nil

local completion = require("poste.http.completion")
local detect_context = completion._test.detect_context

describe("detect_context", function()
  describe("method context", function()
    it("returns 'method' for empty line", function()
      local ctx, extra = detect_context("")
      assert.equals("method", ctx)
      assert.is_nil(extra)
    end)

    it("returns 'method' for whitespace-only line", function()
      local ctx, extra = detect_context("   ")
      assert.equals("method", ctx)
      assert.is_nil(extra)
    end)
  end)

  describe("method_or_header context", function()
    it("returns 'method_or_header' for single word without space", function()
      local ctx, extra = detect_context("GET")
      assert.equals("method_or_header", ctx)
      assert.is_nil(extra)
    end)

    it("returns 'method_or_header' for partial header name", function()
      local ctx, extra = detect_context("Cont")
      assert.equals("method_or_header", ctx)
      assert.is_nil(extra)
    end)
  end)

  describe("header_value context", function()
    it("returns 'header_value' with header name after colon", function()
      local ctx, extra = detect_context("Content-Type: ")
      assert.equals("header_value", ctx)
      assert.equals("Content-Type", extra)
    end)

    it("returns 'header_value' with header name (no space after colon)", function()
      local ctx, extra = detect_context("Accept:")
      assert.equals("header_value", ctx)
      assert.equals("Accept", extra)
    end)

    it("extracts header name with hyphens", function()
      local ctx, extra = detect_context("X-Custom-Header: ")
      assert.equals("header_value", ctx)
      assert.equals("X-Custom-Header", extra)
    end)
  end)

  describe("variable context", function()
    it("returns 'variable' with empty string after {{", function()
      local ctx, extra = detect_context("GET {{")
      assert.equals("variable", ctx)
      assert.equals("", extra)
    end)

    it("returns 'variable' with partial text after {{", function()
      local ctx, extra = detect_context("GET {{ho")
      assert.equals("variable", ctx)
      assert.equals("ho", extra)
    end)

    it("returns 'variable' with $ prefix for magic vars", function()
      local ctx, extra = detect_context("GET {{$")
      assert.equals("variable", ctx)
      assert.equals("$", extra)
    end)

    it("returns 'variable' with $ prefix and partial text", function()
      local ctx, extra = detect_context("GET {{$ti")
      assert.equals("variable", ctx)
      assert.equals("$ti", extra)
    end)

    it("returns nil after closing }}", function()
      local ctx = detect_context("GET {{host}}")
      assert.is_nil(ctx)
    end)

    it("returns 'variable' for unclosed {{ after }}", function()
      local ctx, extra = detect_context("GET {{host}} {{")
      assert.equals("variable", ctx)
      assert.equals("", extra)
    end)
  end)

  describe("nil context (no completion)", function()
    it("returns nil for comment lines starting with #", function()
      local ctx = detect_context("# comment")
      assert.is_nil(ctx)
    end)

    it("returns 'variable' for # @prompt line with unclosed {{", function()
      local ctx, extra = detect_context("# @prompt fruit [{{Get Items.resp")
      assert.equals("variable", ctx)
      assert.equals("Get Items.resp", extra)
    end)

    it("returns nil for # @prompt line with closed {{", function()
      local ctx = detect_context("# @prompt fruit [{{Get Items.response.body}}]")
      assert.is_nil(ctx)
    end)

    it("returns nil for request name lines starting with ###", function()
      local ctx = detect_context("### Request Name")
      assert.is_nil(ctx)
    end)

    it("returns nil for comment lines starting with --", function()
      local ctx = detect_context("-- comment")
      assert.is_nil(ctx)
    end)

    it("returns nil for @var definition lines", function()
      local ctx = detect_context("@var = value")
      assert.is_nil(ctx)
    end)

    it("returns nil for lines with ://", function()
      local ctx = detect_context("http://example.com")
      assert.is_nil(ctx)
    end)

    it("returns nil after complete method followed by space", function()
      local ctx = detect_context("GET ")
      assert.is_nil(ctx)
    end)

    it("returns nil for lines with space but no colon", function()
      local ctx = detect_context("some text")
      assert.is_nil(ctx)
    end)
  end)

  describe("edge cases", function()
    it("handles leading whitespace", function()
      local ctx, extra = detect_context("  Content-Type: ")
      assert.equals("header_value", ctx)
      assert.equals("Content-Type", extra)
    end)

    it("handles tabs in whitespace", function()
      local ctx, extra = detect_context("\tAccept: ")
      assert.equals("header_value", ctx)
      assert.equals("Accept", extra)
    end)
  end)
end)
