### List users
GET {{base_url}}/users
Authorization: Bearer ***

### Create user
POST {{base_url}}/users
Content-Type: application/json
Authorization: Bearer ***

{"name": "John", "email": "john@test.com"}

### Get user by ID
GET {{base_url}}/users/42
Authorization: Bearer ***
