
@base_url = https://postman-echo.com

### Get Items
GET {{base_url}}/get?items[]=apple&items[]=banana&items[]=cherry&items[]=date&items[]=elderberry

### Select Fruit
# @prompt fruit [{{Get Items.response.body.args.items}}]
GET {{base_url}}/get?fruit={{fruit}}

### Static Options
# @prompt method [GET, POST, PUT, DELETE]
GET https://httpbin.org/get?method={{method}}

### Text Input
# @prompt username
GET https://httpbin.org/get?user={{username}}
