
@base_url = https://postman-echo.com

### jq
GET https://api.github.com/repos/jqlang/jq/commits?per_page=5

### Select items
@key = fruit
<<item [{{jq.response.body.[].parents[].sha}}]
GET {{base_url}}/get?{{key}}={{item}}

### Get Items
GET {{base_url}}/get?items[]=apple&items[]=banana&items[]=cherry&items[]=date&items[]=elderberry

### Select Fruit
<<fruit [{{Get Items.response.body.args.items}}]
GET {{base_url}}/get?fruit={{fruit}}

### Static Options
<<method [GET, POST, PUT, DELETE]
GET https://httpbin.org/get?method={{method}}

### Text Input
<<username
GET https://httpbin.org/get?user={{username}}
