### Login
POST https://httpbin.org/post
Content-Type: application/json

{
  "username": "admin",
  "password": "secret123"
}

### Get User Profile
GET https://httpbin.org/get?user={{Login.response.body.json.username}}
Accept: application/json

### Get User Orders
GET https://httpbin.org/get?user={{Login.response.body.json.username}}&token={{Login.response.body.url}}
Accept: application/json

### Get Response Header
GET https://httpbin.org/get?content_type={{Login.response.headers.content-type}}
Accept: application/json

### Chained Request
GET https://httpbin.org/get?previous={{Get User Profile.response.body.url}}
Accept: application/json
